---
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Etc/UTC
    volumes:
      - /home/arruser/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped